---
name: 'Build'

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
    paths-ignore:
      - '*.git**'
      - '**.md'
      - '**.yml'
      - 'LICENSE'

jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Get tag name'
        if: startsWith(github.ref, 'refs/tags/')
        run: 'echo "MODULE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV'
      - name: 'Get commit sha'
        if: startsWith(github.ref, 'refs/heads/')
        run: 'echo "MODULE_VERSION=${GITHUB_SHA}" >> $GITHUB_ENV'
      - name: 'Create module archive'
        uses: 'TheDoctor0/zip-release@v0.3.0'
        with:
          filename: 'unifiednlp-aosp-enabler-${{ env.MODULE_VERSION }}.zip'
          exclusions: '*.git* *.md *.yml LICENSE'
      - name: 'Upload the build artifact'
        uses: 'actions/upload-artifact@v2'
        with:
          name: 'unifiednlp-aosp-enabler'
          path: 'unifiednlp-aosp-enabler-${{ env.MODULE_VERSION }}.zip'
  publish:
    name: 'Publish'
    runs-on: 'ubuntu-latest'
    needs: 'build'
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Get tag name'
        run: 'echo "MODULE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV'
      - name: 'Download the build artifact'
        uses: 'actions/download-artifact@v2'
        with:
          name: 'unifiednlp-aosp-enabler'
      - name: 'Create GitHub Release'
        uses: 'anton-yurchenko/git-release@v3.1.2'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          DRAFT_RELEASE: 'false'
          PRE_RELEASE: 'false'
          CHANGELOG_FILE: 'CHANGELOG.md'
          ALLOW_EMPTY_CHANGELOG: 'true'
          ALLOW_TAG_PREFIX: 'true'
        with:
          args: |
            unifiednlp-aosp-enabler-${{ env.MODULE_VERSION }}.zip
